name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Fetch Submodules
      run: |
        git submodule init
        git submodule update
        
    - name: Get
      run: go get
    
    - name: Build
      run: go build
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: combcore
        path: combcore
